#!/bin/bash

cat <<EOF | sudo tee /lib/systemd/system/riemann-dash.service > /dev/null
[Unit]
Description=Riemann Dashboard Service
After=network.target

[Service]
WorkingDirectory=/etc/riemann
ExecStart=/usr/local/bin/riemann-dash
ExecStop=/usr/bin/killall riemann-dash

[Install]
WantedBy=multi-user.target

EOF

sudo systemctl enable riemann-dash.service
sudo systemctl start riemann-dash.service
