#!/bin/bash
JUPYTERHUB_USER=jupyterhub
JUPYTERHUB_GROUP=jupyterhub
USERS="donatello leonardo michelangelo raphael splinter"
SUDOER_FILE=/etc/sudoers.d/17-jupyterhub-users
JUPYTERHUB_CONFIG_FILE=/etc/jupyterhub_config.py

# install jupyterhub and notebook
sudo apt-get update
sudo apt-get install -y npm nodejs-legacy python3-pip
sudo npm install -g configurable-http-proxy
sudo pip3 install --upgrade pip
sudo pip3 install --upgrade jupyterhub notebook

# add user
sudo useradd ${JUPYTERHUB_USER}
for user in ${USERS}; do
  sudo useradd -m -p $(openssl passwd -1 pizzaninjaturtles) -s /bin/bash -G ${JUPYTERHUB_GROUP} ${user}
done

# configure jupyterhub to run without root privileges
sudo pip3 install sudospawner
sudo usermod -aG shadow ${JUPYTERHUB_USER}

cat <<EOT | sudo tee 17-jupyterhub-users.tmp
Runas_Alias JUPYTER_USERS = `echo ${USERS} | sed -e 's/ /, /g'`
Cmnd_Alias JUPYTER_CMD = /usr/local/bin/sudospawner
jupyterhub ALL=(JUPYTER_USERS) NOPASSWD:JUPYTER_CMD
EOT
sudo visudo -c -f 17-jupyterhub-users.tmp && sudo mv 17-jupyterhub-users.tmp ${SUDOER_FILE}

cat <<EOT | sudo tee ${JUPYTERHUB_CONFIG_FILE}
c.JupyterHub.spawner_class = 'sudospawner.SudoSpawner'
c.Spawner.cmd = ['/usr/local/bin/sudospawner']
EOT
